force-app/main/default/objects/QueueCounter__c/QueueCounter__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds a counter for queue</description>
    <label>QueueCounter</label>
</CustomObject>

force-app/main/default/objects/QueueCounter__c/fields/QueueNumber__c.field-meta.xml
<CustomField>
    <fullName>QueueNumber__c</fullName>
    <label>QueueNumber</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CSTQueueIncrement.cls
global with sharing class CSTQueueIncrement {

	@InvocableMethod
    public static List<List<Decimal>> doCSTIncrement() {
        
        
         QueueCounter__c CSTCount = [select Name, QueueNumber__c from QueueCounter__c 
                                WHERE Name = 'CST' LIMIT 1];


        CSTCount.QueueNumber__c = CSTCount.QueueNumber__c + 1;
        upsert CSTCount;

        Decimal result = CSTCount.QueueNumber__c;
        List<Decimal> listofDecimal = new List<Decimal>();
        listofDecimal.add(result);



        List<List<Decimal>> ListofDecimals = new List<List<Decimal>>();

        ListofDecimals.add(listofDecimal);
      

        return ListofDecimals;         

    }
}